# Project information
site_name: Zabbix 7 Monitoring
site_url: https://trikke76.github.io/Zabbix-Book
site_author: Patrik Uytterhoeven and all github contributors
site_description: An open-source Zabbix book
copyright: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License

# Repository
repo_name: trikke76
repo_url: https://github.com/trikke76/Zabbix-Book
edit_uri: edit/master/docs
docs_dir: docs

# Navigation
nav:
  - Welcome: 'index.md'
  - 'Getting started':
    - installation/Requirements.md
    - installation/installing-zabbixdb.md
    - installation/installing-zabbix.md
    - installation/installing-zabbix-ha.md
  - 'The basics':
    - configuration/Dashboard.md
    - configuration/zabbix-users.md
    - configuration/zabbix-hosts.md
    - configuration/zabbix-hostgroups.md
    - configuration/zabbix-interfaces.md
    - configuration/zabbix-templates.md
    - configuration/zabbix-items.md
    - configuration/zabbix-triggers.md
    - configuration/zabbix-macros.md
    - configuration/zabbix-dataflow.md
    - configuration/zabbix-agent.md
  - 'Problem detection':
    - problems/zabbix-triggers.md
  - 'Taking action when problems come':
    - actions/zabbix-eventactions.md
  - 'Managing permissions':
    - permissions/managing-permissions.md
  - 'Visualising Problems':
     - visualising/Visualising-our-problems.md
  - 'Automating configuration':
    - automation/automating-configuration.md
  - 'VMWare monitoring':
    - vmware/vmware-monitoring.md
  - 'Monitoring websites':
    - websites/monitoring-websites.md
  - 'Monitoring SNMP, IPMI and JAVA':
    - extra-monitoring/SNMP-monitoring.md
    - extra-monitoring/JAVA-monitoring.md
    - extra-monitoring/IPMI-monitoring.md
  - 'Authentication':
    - authentication/zabbix-http.md
    - authentication/zabbix-ldap.md
    - authentication/zabbix-saml.md
    - authentication/zabbix-mfa.md
  - 'Monitoring with Proxies':
    - proxies/installing-proxies.md
    - proxies/active-proxy.md
    - proxies/passive-proxy.md
    - proxies/loadbalancing-proxies.md
  - 'Securing Zabbix':
    - security/securing-zabbix.md
  - 'Maintaining Zabbix':
    - maintenance/maintaining-zabbix.md
  - 'Monitoring Windows':
    - windows/monitoring-windows.md
  - 'Zabbix API':
    - api/zabbix-api.md
  - 'Zabbix Projects':
    - project/modbus.md

theme:
   language: en
   name: material
   custom_dir: docs/overrides
   font:
     text: Roboto
     code: Nunito
   icon:
     logo: material/library
   features:
     - header.autohide
     - navigation.sections
#     - navigation.instant
     - navigation.expand
   palette:
     - scheme: default
       primary: blue
       accent: blue
       toggle:
         icon: material/toggle-switch-off-outline
         name: Switch to dark mode
     - scheme: slate
       primary: light blue
       accent: light blue
       toggle:
         icon: material/toggle-switch
         name: Switch to light mode

# Plugins
plugins:
  - search
  - i18n:
      reconfigure_material: true
      fallback_to_default: true
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: true
        - locale: nl
          name: Nederlands
          build: true
          nav_translations:
            Welcome: Welkom
            Getting started: Aan de slag

  - print-site:
      add_to_navigation: false
      print_page_title: 'Print Book'
      add_print_site_banner: true
      print_site_banner_template: "docs/assets/templates/custom_banner.tpl"
      # Table of contents
      add_table_of_contents: true
      toc_title: 'Table of Contents'
      toc_depth: 6
      # Content-related
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: "docs/assets/templates/custom_cover_page.tpl"
      path_to_pdf: ""
      include_css: true
      enabled: true
      exclude:

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - def_list
  - meta
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.blocks.admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.progressbar
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
