# Project information
site_name: Zabbix Book
site_url: https://trikke76.github.io/Zabbix-Book
site_author: Patrik Uytterhoeven

# Repository
repo_name: trikke76
repo_url: https://github.com/trikke76/Zabbix-Book
edit_uri: edit/master/docs
docs_dir: docs

# Navigation
nav:
  - Welcome: 'index.md'
  - 'Getting started':
    - installation/Requirements.md
    - installation/installing-zabbixdb.md
    - installation/installing-zabbix.md
    - installation/installing-zabbix-ha.md
  - 'The basics':
    - configuration/Dashboard.md
    - configuration/zabbix-users.md
    - configuration/zabbix-hosts.md
    - configuration/zabbix-hostgroups.md
    - configuration/zabbix-interfaces.md
    - configuration/zabbix-templates.md
    - configuration/zabbix-items.md
    - configuration/zabbix-triggers.md
    - configuration/zabbix-macros.md
    - configuration/zabbix-dataflow.md
    - configuration/zabbix-agent.md
  - 'Problem detection':
    - problems/zabbix-triggers.md
  - 'Taking action when problems come':
    - actions/zabbix-eventactions.md
  - 'Managing permissions':
    - permissions/managing-permissions.md
  - 'Visualising Problems':
     - visualising/Visualising-our-problems.md
  - 'Automating configuration':
    - automation/automating-configuration.md
  - 'VMWare monitoring':
    - vmware/vmware-monitoring.md
  - 'Monitoring websites':
    - websites/monitoring-websites.md
  - 'Monitoring SNMP, IPMI and JAVA':
    - extra-monitoring/SNMP-monitoring.md
    - extra-monitoring/JAVA-monitoring.md
    - extra-monitoring/IPMI-monitoring.md
  - 'Authentication':
    - authentication/zabbix-http.md
    - authentication/zabbix-ldap.md
    - authentication/zabbix-saml.md
    - authentication/zabbix-mfa.md
  - 'Monitoring with Proxies':
    - proxies/installing-proxies.md
    - proxies/active-proxy.md
    - proxies/passive-proxy.md
    - proxies/loadbalancing-proxies.md
  - 'Securing Zabbix':
    - security/securing-zabbix.md
  - 'Maintaining Zabbix':
    - maintenance/maintaining-zabbix.md
  - 'Monitoring Windows':
    - windows/monitoring-windows.md
  - 'Zabbix API':
    - api/zabbix-api.md
  - 'Zabbix Projects':
    - project/modbus.md

theme:
   language: en
   name: material
   font:
     text: Roboto
     code: Nunito
   icon:
     logo: material/library
   features:
     - header.autohide
     - navigation.sections
     - navigation.instant
     - navigation.expand
   palette:
     - scheme: default
       primary: blue
       accent: blue
       toggle:
         icon: material/toggle-switch-off-outline
         name: Switch to dark mode
     - scheme: slate
       primary: light blue
       accent: light blue
       toggle:
         icon: material/toggle-switch
         name: Switch to light mode


# Plugins
plugins:
  - search
  - with-pdf: #add only if you like to build a pdf file
      author: Patrik Uytterhoeven
      copyright: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License
      #
      #cover: false
      #back_cover: true
      cover_title: Zabbix 7 Monitoring
      cover_subtitle: Enterprise Monitoring With Zabbix
      #custom_template_path: TEMPLATES PATH
      #
      #toc_title: TOC TITLE TEXT
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      #exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      #render_js: true
      #headless_chrome_path:
      #
      output_path: ../zabbix-7-book.pdf
      #enabled_if_env: ENABLE_PDF_EXPORT
      #
      #debug_html: true
      #show_anchors: true
      #verbose: true
# alternative pdf solution https://github.com/orzih/mkdocs-with-pdf
#  - page-to-pdf


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - def_list
  - meta
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.blocks.admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
#  - pymdownx.emoji:
#      emoji_index: !!python/name:material.extensions.emoji.twemoji
#      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.progressbar
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
